<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>PictureTool</AssemblyName>
    <StartupObject>PictureTool.Program</StartupObject>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
    <Version>2.0.0</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RollForward>LatestMinor</RollForward>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\app.ico" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="PictureTool.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Clowd.Squirrel" Version="2.11.1" />
  </ItemGroup>
</Project>

